const Countries = {
  Afghanistan: 'AFG',
  Albania: 'ALB',
  Algeria: 'DZA',
  Andorra: 'AND',
  Angola: 'AGO',
  Argentina: 'ARG',
  Aruba: 'ABW',
  Australia: 'AUS',
  Austria: 'AUT',
  Azerbaijan: 'AZE',
  Bahrain: 'BHR',
  Bangladesh: 'BGD',
  Barbados: 'BRB',
  Belgium: 'BEL',
  Belize: 'BLZ',
  Bermuda: 'BMU',
  Bolivia: 'BOL',
  'Bosnia and Herzegovina': 'BIH',
  Botswana: 'BWA',
  Brazil: 'BRA',
  Brunei: 'BRN',
  Bulgaria: 'BGR',
  'Burkina Faso': 'BFA',
  Burundi: 'BDI',
  Cameroon: 'CMR',
  Canada: 'CAN',
  'Cape Verde': 'CPV',
  Chad: 'TCD',
  Chile: 'CHL',
  China: 'CHN',
  Colombia: 'COL',
  'Costa Rica': 'CRI',
  Croatia: 'HRV',
  Cuba: 'CUB',
  Cyprus: 'CYP',
  'Czech Republic': 'CZE',
  'Democratic Republic of the Congo': 'COD',
  Denmark: 'DNK',
  Djibouti: 'DJI',
  Dominica: 'DMA',
  'Dominican Republic': 'DOM',
  Ecuador: 'ECU',
  Egypt: 'EGY',
  'El Salvador': 'SLV',
  Estonia: 'EST',
  Ethiopia: 'ETH',
  Finland: 'FIN',
  France: 'FRA',
  Gabon: 'GAB',
  Gambia: 'GMB',
  Germany: 'DEU',
  Ghana: 'GHA',
  Greece: 'GRC',
  Greenland: 'GRL',
  Guam: 'GUM',
  Guatemala: 'GTM',
  Guyana: 'GUY',
  Honduras: 'HND',
  'Hong Kong': 'HKG',
  Hungary: 'HUN',
  Iceland: 'ISL',
  India: 'IND',
  Indonesia: 'IDN',
  Iran: 'IRN',
  Iraq: 'IRQ',
  Ireland: 'IRL',
  Israel: 'ISR',
  Italy: 'ITA',
  Jamaica: 'JAM',
  Japan: 'JPN',
  Jordan: 'JOR',
  Kazakhstan: 'KAZ',
  Kenya: 'KEN',
  Kuwait: 'KWT',
  Kyrgyzstan: 'KGZ',
  Laos: 'LAO',
  Lebanon: 'LBN',
  Lesotho: 'LSO',
  Libya: 'LBY',
  Luxembourg: 'LUX',
  Macao: 'MAC',
  Madagascar: 'MDG',
  Malawi: 'MWI',
  Malaysia: 'MYS',
  Mali: 'MLI',
  Mauritania: 'MRT',
  Mauritius: 'MUS',
  Mexico: 'MEX',
  Moldova: 'MDA',
  Mongolia: 'MNG',
  Morocco: 'MAR',
  Mozambique: 'MOZ',
  Myanmar: 'MMR',
  Namibia: 'NAM',
  Netherlands: 'NLD',
  'New Zealand': 'NZL',
  Nicaragua: 'NIC',
  Niger: 'NER',
  Nigeria: 'NGA',
  Norway: 'NOR',
  Oman: 'OMN',
  Pakistan: 'PAK',
  'Palestinian Territory': 'PSE',
  Panama: 'PAN',
  'Papua New Guinea': 'PNG',
  Paraguay: 'PRY',
  Peru: 'PER',
  Philippines: 'PHL',
  Poland: 'POL',
  Portugal: 'PRT',
  'Puerto Rico': 'PRI',
  Qatar: 'QAT',
  Romania: 'ROU',
  Russia: 'RUS',
  Rwanda: 'RWA',
  'San Marino': 'SMR',
  'Saudi Arabia': 'SAU',
  Serbia: 'SRB',
  Seychelles: 'SYC',
  'Sierra Leone': 'SLE',
  Singapore: 'SGP',
  Slovakia: 'SVK',
  Slovenia: 'SVN',
  'South Africa': 'ZAF',
  'South Korea': 'KOR',
  'South Sudan': 'SSD',
  Spain: 'ESP',
  'Sri Lanka': 'LKA',
  Sudan: 'SDN',
  Swaziland: 'SWZ',
  Sweden: 'SWE',
  Switzerland: 'CHE',
  Syria: 'SYR',
  Taiwan: 'TWN',
  Tanzania: 'TZA',
  Thailand: 'THA',
  'Trinidad and Tobago': 'TTO',
  Tunisia: 'TUN',
  Turkey: 'TUR',
  Uganda: 'UGA',
  Ukraine: 'UKR',
  'United Arab Emirates': 'ARE',
  'United Kingdom': 'GBR',
  'United States': 'USA',
  Uruguay: 'URY',
  Uzbekistan: 'UZB',
  Venezuela: 'VEN',
  Vietnam: 'VNM',
  Zambia: 'ZMB',
  Zimbabwe: 'ZWE',
};

export {Countries};
